name: Examples

on:
  push:
    branches:
      - 'master'
    paths-ignore:
      - 'docs/**'
      - '.github/ISSUE_TEMPLATE/*'
      - '*.md'
      - '*.nimble'
      - '.gitignore'
      - 'LICENSE'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
        nim_version:
          - 'stable'
    env:
      TIMEOUT_EXIT_STATUS: 124
    steps:
      - uses: actions/checkout@v3
      - name: Cache nimble
        id: cache-nimble
        uses: actions/cache@v3
        with:
          path: ~/.nimble
          key: ${{ runner.os }}-nimble-${{ hashFiles('*.nimble') }}
      - uses: jiro4989/setup-nim-action@v1
        with:
          nim-version: ${{ matrix.nim_version }}
      
      - name: Install Dependencies
        run: |
          nimble refresh
          nimble install -y regex
          nimble install -y cligen
          nimble install -y httpx
      
      - name: Hello World
        run: |
          cd examples/hello_world
          nim c -d:httpx main
          cd ../../
        shell: bash
      
      - name: TODO App
        run: |
          cd examples/todo
          nim js main
          cd ../../
        shell: bash
